sources:
  - name: inventorymanager
    handler:
      graphql:
        endpoint: https://api.studio.thegraph.com/query/92897/inventory-manager-2/version/latest

documents:
  - ./graphql/GetSupplierByName.gql
  - ./graphql/GetItemsAdded.gql
  - ./graphql/GetSuppliers.gql
  - ./graphql/GetItems.gql
  - ./graphql/GetStockDecreasedAggregationDay.gql
  - ./graphql/GetStockDecreasedAggregationHour.gql
  - ./graphql/GetStockDecreasedData.gql
